version: "3.7"

services:
  # Postgres db container
  db:
    image: "postgres:13-alpine"
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "PGUSER=postgres"
    ports:
      - "5432:5432"