version: "3.7"

services:
  web:
    container_name: app
    build: ./
    command: sh -c "python manage.py migrate && python manage.py loaddata db_fixtures.json && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db
  # Postgres db container
  db:
    container_name: postgres
    image: "postgres:13-alpine"
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "PGUSER=postgres"
    ports:
      - "5432:5432"